
docker run -it -d \
  --label traefik.http.routers.fordmicrofinance.rule=Host\(\`fordmicrofinance.loan-pocket.com\`\) \
  --label traefik.http.routers.fordmicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.fordmicrofinance.tls=true \
  --label traefik.http.routers.fordmicrofinance.service=fordmicrofinance-credit-http \
  --label traefik.http.services.fordmicrofinance-credit-http.loadbalancer.server.port=80 \
  --name fordmicrofinance \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft_nack:may19 


   